# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2bd64c9a0bc81c25db455a2827636a86"
name = "EasyAccess-Year Make Model"
handle = "easyacess-year-make-model"
application_url = "https://r-programming-supplements-grey.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "navjot-work.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access.admin]
direct_api_mode = "offline"
embedded_app_direct_api_access = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products"
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://r-programming-supplements-grey.trycloudflare.com/auth/callback",
  "https://r-programming-supplements-grey.trycloudflare.com/auth/shopify/callback",
  "https://r-programming-supplements-grey.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
